[project]
name = "python"
version = "0.1.0"
description = "Event sourcing example in Python"
readme = "README.md"
requires-python = ">=3.9.9"
dependencies = [
    "pytest>=8.4.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
]
